---
- name: Symfony
  tasks:
    - name: Show compiled env file
      tags: dotenv-show
      block:
        - command: 'cat {{ symfony_folder }}/.env.local.php'
          register: compiled_dotenv_content
        - debug:
            var: compiled_dotenv_content.stdout
