---

- name: Clear Symfony cache
  tags: clear-cache
  ansible.builtin.command: 'echo "Clear Symfony cache"'
  notify: Clear Symfony cache
- name: Show compiled env file
  tags: dotenv-show
  block:
    - name: Retrieve compiled env file content
      ansible.builtin.command: 'cat {{ symfony_folder }}/.env.local.php'
      register: compiled_dotenv_content
    - name: Display compiled env file content
      ansible.builtin.debug:
        var: compiled_dotenv_content.stdout
